### ISSUE TITLE
[Bug] Fix the dreaded everyping bug

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [Jan0660/Taco#10]
Apparently you can ping @everyone from the revolt server and have it go through as an @everyone on the discord server.

**Comment by sussycatgirl** [comment]
it doesn't ping anyone though?
![7FF409D2-6E39-4CD6-AAAD-0431FCEA40DA](https://user-images.githubusercontent.com/26145882/155268074-e6a3ae95-e0ca-4852-8ebb-c49971a84b18.jpeg)

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
nevermind, my source of what happens discord-side was a meme and an owner being pissed off

**Comment by Jan0660** [comment]
It is the year of 2035
Microsoft's employee count has increased more than five-fold since 2021
Why? Has Microsoft taken over every major tech company?
No.
As meme recycling went increased and increased. Human intelligence has only decreased and decreased.
Dozens of millions of people every day give feedback based on inaccurate, outdated and often very cringe memes.

---

Did you really see a meme and create an issue before verifying it actually is there? I appreciate creating issues but please for the love of all gods verify they actually exist
